
name: Open a new Issue
description: For reporting a bug, proposing a new feature, enhancing an existing one, asking a question...
title: "[Candidate]: "
labels: candidate
body:
  - type: textarea
    id: descr
    attributes:
      label: Dear user, welcome to the Fed-BioMed project !
      description: "*Please keep the `candidate` label when creating your issue: this help us to tag your issue appropriately. We will get back to you as soon as possible !*"
      placeholder: Your question, proposal, bug, ...
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: [Definition Of Done](https://example.com) and [Coding Rules](https://example.com)
      description: By submitting this issue, you agree to follow our [Definition Of Done](https://example.com) and our [Coding Rules](https://example.com)
      options:
        - label: I agree to follow this project's Definition Of Done and Coding Rules
          required: true