name: FBM-build-test
run-name: FBM-build-test
on: [push]
jobs:
  build-test:
    runs-on: macos-13
    steps:
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: 3.9
          miniconda-version: "latest"
      - uses: docker-practice/actions-setup-docker@master
        timeout-minutes: 12
      - run: |
          set -x
          docker version
          docker run --rm hello-world
      - name: FBM_App_Setup
        run: |
          actions/checkout@v3
          ./scripts/configure_conda researcher network
          ./scripts/fedbiomed_run network
      - name: FBM_Tests  
        run: PYTHONPATH=${PYTHONPATH:-$PWD} /usr/bin/conda run -n fedbiomed-researcher nosetests -w tests --cover-xml --cover-erase --with-coverage --cover-package=fedbiomed --with-xunit -v --process-restartworker
      - name: FBM_Shutdown
        run: ./scripts/fedbiomed_run network stop
