name: FBM-build-test
run-name: FBM-build-test
on:   
  pull_request:
    types:
      - opened
jobs:
  build-test:
    runs-on: [self-hosted, macOS]
    steps:
      - uses: actions/checkout@v3
      - name: FBM_App_Setup
        run: |
          source $HOME/.zprofile
          source $HOME/.zshrc
          ./scripts/configure_conda researcher network
          ./scripts/fedbiomed_run network
      - name: FBM_Tests  
        run: |
          source $HOME/.zprofile
          source $HOME/.zshrc
          PYTHONPATH=${PYTHONPATH:-$PWD} conda run -n fedbiomed-researcher nosetests -w tests --cover-xml --cover-erase --with-coverage --cover-package=fedbiomed --with-xunit -v --process-restartworker
      - name: FBM_Shutdown
        run: |
          source $HOME/.zprofile
          source $HOME/.zshrc  
          ./scripts/fedbiomed_run network stop
      
      - name: XUnit Viewer
        env:
          RESULTS_PATH: ./nosetests.xml
        id: xunit-viewer
        uses: AutoModality/action-xunit-viewer@v1  
      - name: Attach the report
        uses: actions/upload-artifact@v1
        with:
           name: ${{ steps.xunit-viewer.outputs.report-name }}
           path: ${{ steps.xunit-viewer.outputs.report-dir }}

