name: FBM-build-test
run-name: FBM-build-test
on: [push]
jobs:
  build-test:
    runs-on: macos-13
    steps:
      - name: FBM_Basic_Setup
        run: |
          uses: conda-incubator/setup-miniconda@v2
          with:
            auto-update-conda: true
            python-version: 3.9
            miniconda-version: "latest"
          brew install docker
          colima start
      - name: FBM_App_Setup
        run: |
# useful?         export PATH=${PATH}:/usr/local/bin
#          echo $PATH
          actions/checkout@v3
          ./scripts/configure_conda researcher network
          ./scripts/fedbiomed_run network
      - name: FBM_Tests  
        run: PYTHONPATH=${PYTHONPATH:-$PWD} /usr/bin/conda run -n fedbiomed-researcher nosetests -w tests --cover-xml --cover-erase --with-coverage --cover-package=fedbiomed --with-xunit -v --process-restartworker
      - name: FBM_Shutdown
        run: ./scripts/fedbiomed_run network stop
