name: Documentation Build Test
on:   
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - closed
      - assigned 
      - ready-for-review

    branches:
      - master
      - develop

jobs:
  paths-filter:
    # Job to see merge reqeust contains changes related to documentation
    # If so, the job `build-doc` will be triggerred, if not `build-doc` 
    # will be skipped 
    name: filter-docs-related-file-changes
    runs-on: ubuntu-latest
    outputs:
      is_doc_related_file_changed: ${{ steps.filter.outputs.docs }}
    if: github.event.pull_request.draft == false
    steps:
    - uses: actions/checkout@v2
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          docs:
            - 'fedbiomed/**'
            - 'scripts/docs/**'
            - 'docs/**'
            - 'envs/development/**'
            - 'mkdocs.yml'
            - 'README.md'

    # run only if 'workflows' files were changed
    - name: Changes related to docs
      if: steps.filter.outputs.docs == 'true'
      run: echo true

    # run only if not 'workflows' files were changed
    - name: No changes related to docs
      if: steps.filter.outputs.docs != 'true'
      run: echo false


  build-doc:
    name: test-documentation-build
    runs-on: ubuntu-latest
    needs: paths-filter
    # if: ${{ github.event_name == 'push' || github.event.pull_request.opened == true }}
    if: | 
      ( github.event.pull_request.draft == false && needs.paths-filter.outputs.is_doc_related_file_changed == 'true' )
    steps:
      - name: Checkout to repository
        uses: actions/checkout@v3
    
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11' 

      - name: Install Dependencies
        run: pip install -r envs/development/docs-requirements.txt

      - name: Build documentation
        # Version number for testing purposes should respect to standart which is vMajor.Minor.Patch 
        run: scripts/docs/fedbiomed_doc.sh --build-dir build-repo --build-main --build-current-as v1.0.1 