name: Documentation Build Test
on:
  push:
    paths-ignore:
      - README.md
      - CHANGELOG.md # Should never be edited anyway
      - .gitignore
      - .github/**
      - envs/vpn/**
      - gui/**
      - notebooks/**
      - tests/**
    pull_request:
      types:
        - opened
      branches:
        - master
  
  jobs:
    build:
      name: Testing build of documentation
      runs-on: ubuntu-latest
      if: ${{ github.event_name == 'push' || github.event.pull_request.opened == true }}
      steps:
      - name: Checkout to repositort
        uses: actions/checkout@v3
      
      - name: Setup python
        uses: actions/setup-python@v4
        with:
            python-version: '3.11' 

      - name: Install Dependencies
        run: pip install -r envs/development/docs-requirements.txt


      - name: Build documentation
        run: scripts/docs/fedbiomed_doc.sh --build-dir build-repo --build-main