name: Publish changes in pushed to master
on:
  push:
    branches:
      - master
    
jobs:
  build-doc:
    name: Publish main documentation
    environment: github-pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to repositort
        uses: actions/checkout@v3
      
      - name: Checkout tools repo
        uses: actions/checkout@v3
        with:
          repository: fedbiomed/docs
          ssh-key: ${{ secrets.STORE_DOCS_REPO_KEY }}
          path: build-repo
      - name: git
        run: |
          # setup the username and email. I tend to use 'GitHub Actions Bot' with no email by default
          git --version
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "<>"
          git fetch --tags
          git fetch origin master
          git checkout master
          git tag -l
      - name: Setup python
        uses: actions/setup-python@v4
        with:
            python-version: '3.11' 

      - name: Install Dependencies
        run: pip install -r envs/development/docs-requirements.txt


      - name: Build documentation
        run: scripts/docs/fedbiomed_doc.sh --build-dir build-repo --build-main

      - name: Push change to docs repo
        run: |
          cd build-repo
          git add .
          git commit -m "Deploy action: documentation build/update" 
          git pull --no-edit --no-rebase  
          if [ ! git commit -a -m "Pulling recent changes" ]; then
            echo "o changes to commit"
          fi
          git push
          git push
          cd ../

      - name: Prepare public web content
        run: |
          mkdir public
          rsync -q -av --checksum --progress build-repo/. public/ --exclude CNAME --exclude .nojekyll --exclude .ssh --exclude .git --exclude .github

      # Upload built documentation source code
      - name: Upload Artificat
        uses: actions/upload-pages-artifact@v1
        with:
          path: 'public'


  deploy:
    name: Deploy Documentation
    # Add a dependency to the build job
    needs: build-doc

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2 # or the latest "vX.X.X" version tag for this action
